# NumPy Essential Part 1

In [1]:
import numpy as np

In [2]:
my_list = [-1, 0, 1]

In [3]:
my_list, type(my_list)

([-1, 0, 1], list)

In [4]:
my_array = np.array(my_list)

In [5]:
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [6]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_matrix, type(my_matrix)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [8]:
matrix_one = np.array(my_matrix)

In [9]:
matrix_one, type(matrix_one)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [10]:
my_tuples = (-1,0,1)

In [11]:
my_array_t = np.array(my_tuples)

In [12]:
my_array_t, type(my_array_t)

(array([-1,  0,  1]), numpy.ndarray)

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.arange(0, 11, 2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [16]:
np.linspace(1, 15, 15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [17]:
np.linspace(1, 15, 15, retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.]),
 1.0)

In [18]:
np.linspace(1, 15, 30, retstep=True)

(array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
         3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
         5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
         8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
        10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
        13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ]),
 0.4827586206896552)

In [20]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(3)

array([0.91100408, 0.64811107, 0.1399391 ])

In [25]:
np.random.rand(3, 2)

array([[0.6259005 , 0.83221049],
       [0.67815185, 0.86140528],
       [0.7157639 , 0.72773737]])

In [28]:
np.random.randn(3, 5)

array([[ 1.0521665 ,  0.05006936,  0.41002478,  1.06978413,  0.5029975 ],
       [ 0.87064943, -1.86264007, -1.70826285,  0.01342711, -0.9213702 ],
       [ 0.82145336,  1.67285284, -1.68783765,  1.34065357,  0.19763822]])

In [40]:
np.random.randint(1, 100, (4, 10))

array([[81, 38,  7, 85, 37, 73, 80, 51, 36, 69],
       [54, 41, 24, 20, 11, 39, 14, 11, 83, 88],
       [32, 39,  5, 56, 72, 44, 42, 12, 86, 22],
       [81,  6, 83, 12,  6,  9, 35, 61, 66, 22]])

In [41]:
array_arange = np.arange(16)

In [42]:
array_int = np.random.randint(1, 100, 10)

In [43]:
array_arange.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
array_int

array([24, 11, 45, 91, 38, 35, 95, 24, 48, 14])

In [44]:
array_int.max()

95

In [45]:
array_int.min()

11

In [46]:
array_int.argmax()

6

In [48]:
array_int.argmin()

1

In [50]:
array_arange.shape

(16,)

In [51]:
array_arange.size

16

In [52]:
array_arange.dtype

dtype('int64')

In [ ]:
array_arange.reshape()

    
   # NumPy Essential Part 2

In [53]:
array_1d = np.array([10, -2, 0, 2, 17, 106, 200])

In [54]:
array_1d

array([ 10,  -2,   0,   2,  17, 106, 200])

In [55]:
array_1d[0]

10

In [56]:
array_1d[0:3]

array([10, -2,  0])

In [59]:
array_1d[:2], array_1d

(array([10, -2]), array([ 10,  -2,   0,   2,  17, 106, 200]))

In [60]:
array_1d[2:], array_1d

(array([  0,   2,  17, 106, 200]), array([ 10,  -2,   0,   2,  17, 106, 200]))

In [61]:
array_2d = np.arange(24).reshape(4, 6)
array_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
array_2d[row, col]

In [66]:
array_2d[1:3, 1:3]

array([[ 7,  8],
       [13, 14]])